# @package _group_

nq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file:

nq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file:

webq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file:

webq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: